version: '3.8'

fastapi:
    build:
      context: .
    container_name: fastapi
    depends_on:
    - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true
