services:
  fastapi:
      build:
        context: .
      container_name: fastapi
      ports:
        - "8080:8080"
      networks:
        - app-network

networks:
  app-network:
    external: true
