version: '3.8'

services:
  fastapi:
    build:
      context: .
    container_name: fastapi
    depends_on:
      - postgres
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
