"""initial create base location model

Revision ID: 34cbcc4f2b28
Revises: 
Create Date: 2024-11-27 00:50:01.291021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '34cbcc4f2b28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('code_province', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_province', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code_province')
    )
    op.create_table('cities',
    sa.Column('code_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_province', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['code_province'], ['provinces.code_province'], ),
    sa.PrimaryKeyConstraint('code_city')
    )
    op.create_table('districts',
    sa.Column('code_district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['code_city'], ['cities.code_city'], ),
    sa.PrimaryKeyConstraint('code_district')
    )
    op.create_table('villages',
    sa.Column('code_village', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_village', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['code_district'], ['districts.code_district'], ),
    sa.PrimaryKeyConstraint('code_village')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('villages')
    op.drop_table('districts')
    op.drop_table('cities')
    op.drop_table('provinces')
    # ### end Alembic commands ###
