"""create table event, category class,and event image

Revision ID: df108ad02884
Revises: 4e992fd6cef9
Create Date: 2024-11-27 01:01:01.054470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '4e992fd6cef9'
down_revision: Union[str, None] = '34cbcc4f2b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('category_name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('count_views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['eventorganizers.organizer_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_category_association',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_name'], ['event_categories.category_name'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'category_name')
    )
    op.create_table('event_class',
    sa.Column('event_class_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_price', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_class_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_class')
    op.drop_table('event_category_association')
    op.drop_table('events')
    op.drop_table('event_categories')
    
    op.execute("DROP TYPE IF EXISTS eventstatus")
    # ### end Alembic commands ###
