"""create table event, category class, schedule and event image

Revision ID: df108ad02884
Revises: 4e992fd6cef9
Create Date: 2024-11-27 01:01:01.054470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'df108ad02884'
down_revision: Union[str, None] = '4e992fd6cef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('category_name')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('code_province', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_village', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_city'], ['cities.code_city'], ),
    sa.ForeignKeyConstraint(['code_district'], ['districts.code_district'], ),
    sa.ForeignKeyConstraint(['code_province'], ['provinces.code_province'], ),
    sa.ForeignKeyConstraint(['code_village'], ['villages.code_village'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['eventorganizers.organizer_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_category_association',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['category_name'], ['event_categories.category_name'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'category_name')
    )
    op.create_table('event_class',
    sa.Column('event_class_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_price', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_class_id')
    )
    op.create_table('event_images',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='dayofweek'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('event_images')
    op.drop_table('event_class')
    op.drop_table('event_category_association')
    op.drop_table('events')
    op.drop_table('event_categories')
    
    op.execute("DROP TYPE IF EXISTS eventstatus")
    op.execute("DROP TYPE IF EXISTS dayofweek")
    # ### end Alembic commands ###
