"""update users add location and profile event origanizer

Revision ID: e255d0103028
Revises: 6fc9d019fa59
Create Date: 2024-11-26 18:11:36.482201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e255d0103028'
down_revision: Union[str, None] = '6fc9d019fa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventorganizers', sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('code_province', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('code_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('code_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('code_village', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'users', 'villages', ['code_village'], ['code_village'])
    op.create_foreign_key(None, 'users', 'cities', ['code_city'], ['code_city'])
    op.create_foreign_key(None, 'users', 'provinces', ['code_province'], ['code_province'])
    op.create_foreign_key(None, 'users', 'districts', ['code_district'], ['code_district'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'code_village')
    op.drop_column('users', 'code_district')
    op.drop_column('users', 'code_city')
    op.drop_column('users', 'code_province')
    op.drop_column('eventorganizers', 'profile_picture')
    # ### end Alembic commands ###
